name: actions
author: Diego Vasconcelos
description: actions

inputs:
  host:
    description: Database HOST
    required: true
  port:
    description: Database PORT
    required: false
    default: '3306'
  username:
    description: Database username
    required: true
  password:
    description: Database password
    required: true
  database-prefix:
    description: Database prefix
    required: false
    default: test_
  env-name:
    description: Env name to export database var
    required: false
    default: DB_DATABASE

runs:
  using: node24
  main: dist/main/index.js
  post: dist/post/index.js
